### ISSUE TITLE
Large Log File Output

### ISSUE THREAD

**Issue by aperloff** [kpedro88/CondorProduction#2]
The current way of managing the log files is starting to break down at scale. The current scheme is to store stdout, stderr, and condor files in the current working folder and the old version of those for the resubmitted jobs in the "backup" folder. Even with a low number of failures, the working folder can reach hundreds of GB when there are O(20k) jobs.

It would be nice to have some sort of feature to tar up the files for the finished jobs and/or transfer them off-site. Currently the best (only?) place to do this is in jobSubmitter using something like missing mode. However, the ideal place would be in manageJobs. A future merging of these scripts would be ideal, but I understand that is a separate and more long term issue.

**Comment by kpedro88** [comment]
Addressed w/ clean mode: https://github.com/kpedro88/CondorProduction#clean-mode
